[package]
name = "digitally_validate_a_degree"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
identity_iota = { git = "https://github.com/iotaledger/identity.rs.git", tag = "v1.6.0-alpha", features = ["memstore", "domain-linkage", "jpt-bbs-plus", "iota-client", "resolver", "revocation-bitmap", "sd-jwt", "status-list-2021",] }
iota-sdk = { git = "https://github.com/iotaledger/iota.git", package = "iota-sdk", tag = "v0.7.3-rc" }
rand = "0.8.5"
iota-sdk-legacy = { package = "iota-sdk", version = "1.0", default-features = false, features = ["tls", "client", "stronghold"] }
tokio = { version = "1.29", default-features = false, features = ["rt", "macros"] }
serde_json = { version = "1.0", default-features = false }
secret-storage = { git = "https://github.com/iotaledger/secret-storage.git", tag = "v0.1.0" }
identity_stronghold = { git = "https://github.com/iotaledger/identity.rs", branch = "feat/identity-rebased-alpha" }

[[bin]]
name = "create_did"
path = "src/create_did.rs"

[[bin]]
name = "add_verification_method"
path = "src/add_verification_method.rs"


